import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def send_email_notification(to_email, target, findings, report_path, smtp_host="smtp.gmail.com", smtp_port=587, smtp_user=None, smtp_pass=None):
    if not smtp_user or not smtp_pass:
        return False, "SMTP credentials not configured"

    counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for f in findings:
        sev = f.get("severity", "LOW")
        if sev in counts:
            counts[sev] += 1

    subject = f"[WebReaper] Scan Complete: {target} — {counts['CRITICAL']} Critical, {counts['HIGH']} High"

    body = f"""
WebReaper Scan Complete
========================
Target: {target}
Total Findings: {len(findings)}

CRITICAL : {counts['CRITICAL']}
HIGH     : {counts['HIGH']}
MEDIUM   : {counts['MEDIUM']}
LOW      : {counts['LOW']}

Report saved to: {report_path}

Top Critical Findings:
"""
    criticals = [f for f in findings if f.get("severity") == "CRITICAL"]
    for f in criticals[:5]:
        body += f"\n• {f['name']} — {f['url']}"

    body += "\n\nGenerated by WebReaper v1.0 | For authorized use only"

    try:
        msg = MIMEMultipart()
        msg["From"] = smtp_user
        msg["To"] = to_email
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, to_email, msg.as_string())

        return True, "Email sent successfully"
    except Exception as e:
        return False, str(e)
